<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KONTAKTI</name>
   <tag></tag>
   <elementGuidId>57f7d56d-b8a4-49f6-96fa-c18c9a846faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7750ed23-a13e-41bc-b757-f8a20ab626e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/aplikacije/kontakti/</value>
      <webElementGuid>f80e4745-b97d-4fab-8d1f-a2a8e2c026ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONTAKTI</value>
      <webElementGuid>4bd2f20e-a355-48ea-9d5c-0b30fb42e491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;block&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>f4c634e0-57ba-4c09-8dab-442bd65c27f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      <webElementGuid>4546ad64-36f4-4568-adf8-f550b6babd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'KONTAKTI')])[2]</value>
      <webElementGuid>acefaf06-e432-49a4-ab9e-4134bf2117c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKADEMIJA FERI'])[2]/following::a[1]</value>
      <webElementGuid>75cf1539-734a-4f7e-9890-f658b9bc2923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAZISKOVANJE'])[2]/following::a[2]</value>
      <webElementGuid>518faad6-0d28-4a8f-8a2c-5b1d7be92cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapri primarno navigacijo'])[1]/preceding::a[1]</value>
      <webElementGuid>43692772-96d6-4226-83d0-c82c04f1710c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOVICE'])[1]/preceding::a[2]</value>
      <webElementGuid>1636a8e3-b27c-44e8-915e-a22ac03fe489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/aplikacije/kontakti/')])[2]</value>
      <webElementGuid>ecef0104-fd7d-4c59-92dd-d4c043ea3dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/div/ul/li[5]/a</value>
      <webElementGuid>f9680ae3-4dc7-4354-98dd-6a250cdc27a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/aplikacije/kontakti/' and (text() = 'KONTAKTI' or . = 'KONTAKTI')]</value>
      <webElementGuid>be2d3e7c-863a-43fb-bb52-59b439ee81aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
